apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - workflows/react-native-init.yaml
  - workflows/react-native-android-release.yaml

namespace: react-native
labels:
  - includeSelectors: true
    pairs:
      app: react-native
