apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- volumes/react-native.yaml
- volumes/gradle.yaml
- accounts/admin.yaml
- accounts/manager.yaml

# namePrefix: dev-
labels:
- includeSelectors: true
  pairs:
    app: react-native
