apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - volumes/react-native.yaml
  - volumes/gradle.yaml

# namePrefix: dev-
commonLabels:
  app: react-native
