apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  namespace: argo
  name: react-native
spec:
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
    - group: ''
      kind: PersistentVolume
  destinations:
    - name: in-cluster
      namespace: ''
      server: https://kubernetes.default.svc
    - name: in-cluster
      namespace: argo
      server: https://kubernetes.default.svc
    - name: in-cluster
      namespace: react-native
      server: https://kubernetes.default.svc
  sourceRepos:
    - https://github.com/lucasmathioni/react-native
status: {}
