apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  namespace: react-native
  name: android-init
  annotations:
    workflows.argoproj.io/title: '**Android Init**'
    workflows.argoproj.io/description: |
      Executa scripts para preparar o código do volume para builds `Android`.
  labels:
    app: android
spec:
  workflowMetadata:
    annotations:
      workflows.argoproj.io/title: '**Android Init**'
      workflows.argoproj.io/description: |
        Executa scripts para preparar o código do volume para builds `Android`.
    labels:
      app: android
  serviceAccountName: manager
  entrypoint: main
  templates:
    - name: main
      annotations:
        workflows.argoproj.io/display-name: init
      container:
        image: mathone/android:latest
        imagePullPolicy: Never
        workingDir: /source/android
        command: ['sh', '-c']
        args:
          - |
            echo "💬  Verificando Gradle..."
            chmod +x ./gradlew
            ./gradlew clean || exit 1
            echo "💬  Gradlew configurado."

            echo "💬  Preparação finalizada."
        volumeMounts:
          - name: react-native
            mountPath: /source
            subPath: source
          - name: gradle
            mountPath: /opt/.gradle
      volumes:
        - name: react-native
          persistentVolumeClaim:
            claimName: react-native
        - name: gradle
          persistentVolumeClaim:
            claimName: gradle
