apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: react-native-init
  generateName: react-native-init-
  annotations:
    workflows.argoproj.io/title: 'React Native Init'
    workflows.argoproj.io/description: 'Clona o repositório e instala dependências com yarn.'
spec:
  serviceAccountName: manager
  entrypoint: main
  arguments:
    parameters:
      - name: repository-url
        value: https://github.com/lucasmathioni/react-native.git
  templates:
    - name: main
      steps:
        - - name: github-clone
            templateRef:
              name: github-clone
              template: main
            arguments:
              parameters:
                - name: repository-url
                  value: '{{workflow.parameters.repository-url}}'
        - - name: yarn-install
            templateRef:
              name: yarn-install
              template: main
        - - name: android-init
            templateRef:
              name: android-init
              template: main
        - - name: android-clean
            templateRef:
              name: android-clean
              template: main
