apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: react-native-android-release
  generateName: react-native-android-release-
  annotations:
    workflows.argoproj.io/title: 'React Native Android Release'
    workflows.argoproj.io/description: 'Atualiza o código e gera o build de release Android.'
spec:
  serviceAccountName: manager
  entrypoint: main
  dependencies:
    - name: react-native-init
      eventSourceName: argo-events
      eventName: workflow-finished
  templates:
    - name: main
      steps:
        - - name: github-pull
            templateRef:
              name: github-pull
              template: main
        - - name: android-assemble-release
            templateRef:
              name: android-assemble-release
              template: main
