apiVersion: v1
kind: PersistentVolume
metadata:
  name: react-native
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: react-native
  capacity:
    storage: 20Gi
  hostPath:
    path: /data/react-native
  accessModes:
    - ReadWriteOnce
