apiVersion: v1
kind: PersistentVolume
metadata:
  name: gradle
spec:
  storageClassName: gradle
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /opt/.gradle
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gradle
spec:
  storageClassName: gradle
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
