apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  namespace: react-native
  name: github-clone
  annotations:
    workflows.argoproj.io/title: '**Github Clone**'
    workflows.argoproj.io/description: |
      Clona o reposit贸rio definido no argumento `repository-url` na pasta `/source` do volume.
  labels:
    app: github
spec:
  workflowMetadata:
    annotations:
      workflows.argoproj.io/title: '**Github Clone**'
      workflows.argoproj.io/description: |
        Clona o reposit贸rio definido no argumento `repository-url` na pasta `/source` do volume.
    labels:
      app: github
  serviceAccountName: manager
  entrypoint: main
  arguments:
    parameters:
      - name: repository-url
        value: https://github.com/lucasmathioni/react-native.git
  templates:
    - name: main
      annotations:
        workflows.argoproj.io/display-name: clone
      inputs:
        parameters:
          - name: repository-url
      container:
        image: mathone/git:latest
        imagePullPolicy: Never
        command: ['sh', '-c']
        args:
          - |
            if [ -d /source ] && [ "$(ls -A /source)" ]; then
              echo "  Pasta '/source' j谩 existe e cont茅m arquivos, n茫o ser谩 feito clone."
            else
              echo "  Clonando reposit贸rio '${{inputs.parameters.repository-url}}' em '/source'..."
              git clone {{inputs.parameters.repository-url}} /source
              echo "  Reposit贸rio clonado."
            fi
        volumeMounts:
          - name: react-native
            mountPath: /source
            subPath: source
      volumes:
        - name: react-native
          persistentVolumeClaim:
            claimName: react-native
